### ISSUE TITLE
Update UI using latest version of Bootstrap Elements

### ISSUE THREAD

**Issue by prabhuomkar** [nerdyninja/json-coder#28]
- Revamp the project with latest version of **Bootstrap CSS Framework**.
- Use **Bootstrap Components** throughout the site, leaving the JS as it is.
- Add your name in footer by updating the _**designed by**_ section.

**Comment by raajnadar** [comment]
This PR is a good starting point https://github.com/prabhuomkar/json-coder/pull/26

**Comment by mazsam** [comment]
@prabhuomkar could you assign this one to me ?

**Comment by prabhuomkar** [comment]
Yeah you can take it
