### ISSUE TITLE
Change the button colour

### ISSUE THREAD

**Issue by ghost** [nerdyninja/json-coder#4]

**Comment by thepriefy** [comment]
Which button and its color do you want to change?

**Comment by tanya-vedi** [comment]
Please specify the button and its color.

**Comment by chetanya-shrimali** [comment]
@nerdyninja  i would like to work on this. Plz specify the details!!

**Comment by ghost** [comment]
Thanks for your interest. I would like to change overall theme of the json-coder and make it user friendly. So you are free to change overall look of json-coder without actually work on revamping it. You are free to choose your colors and components for the same. Appreciate your response!

**Comment by bxrdy** [comment]
I'd love to take this one! 😃

**Comment by prabhuomkar** [comment]
Outdated. Closing this Issue.
